// <auto-generated />
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BibliotekContext))]
    [Migration("20260128124117_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Bog", b =>
                {
                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ErUdlånt")
                        .HasColumnType("bit");

                    b.Property<string>("Forfatter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Medlemsnummer")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Isbn");

                    b.HasIndex("Medlemsnummer");

                    b.ToTable("Bøger");
                });

            modelBuilder.Entity("Domain.Entities.Medlem", b =>
                {
                    b.Property<int>("Medlemsnummer")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Medlemsnummer");

                    b.ToTable("Medlemmer");
                });

            modelBuilder.Entity("Domain.Entities.Bog", b =>
                {
                    b.HasOne("Domain.Entities.Medlem", null)
                        .WithMany("AktueltLånteBøger")
                        .HasForeignKey("Medlemsnummer");
                });

            modelBuilder.Entity("Domain.Entities.Medlem", b =>
                {
                    b.Navigation("AktueltLånteBøger");
                });
#pragma warning restore 612, 618
        }
    }
}
